### ISSUE TITLE
pop with post hs education data fix

### ISSUE THREAD

**Issue by klinehan1** [uva-bi-sdad/community_example#1]
@hc2cc The population with post high school education data is percentage data and needs to be scaled to be in the range 0-100.  It is currently in decimal format from 0-1.

**Comment by hc2cc** [comment]
Tables va_hdcttr_acs_2015_2019_post_hs_education
va_hd_acs_2015_2019_post_hs_education
va_ct_acs_2015_2019_post_hs_education
va_tr_acs_2015_2019_post_hs_education
are updated in the database
